import Link from "next/link";

const LOGO = "https://vqaaxqvyepouqcrxduiw.supabase.co/storage/v1/object/public/assets/logo.png";

export const metadata = {
  title: "AI Policy — Sparkurio",
  description: "Sparkurio's policy on AI-generated images and why we keep them off the platform.",
};

export default function AIPolicyPage() {
  return (
    <div className="min-h-screen bg-[#FDFCFB]">
      <header className="border-b border-ink/5">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/">
            <img src={LOGO} alt="Sparkurio" className="h-8 w-auto" />
          </Link>
          <Link href="/" className="text-sm text-ink/50 hover:text-ink transition-colors">
            ← Back to Sparkurio
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-12">
          <h1 className="font-serif text-4xl text-ink mb-4">Our AI Policy</h1>
          <p className="text-ink/50 text-sm">Last updated April 2026</p>
        </div>

        <div className="prose prose-ink max-w-none space-y-10 text-ink/80 leading-relaxed">

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">What Sparkurio is for</h2>
            <p>
              Sparkurio is a space for human creativity and inspiration. Every board is a window into
              someone&apos;s genuine taste — the things that actually moved them, photographs they took,
              artwork they love, ideas that stuck. That authenticity is the whole point. When you browse
              here, you should be able to trust that what you&apos;re seeing came from a real person&apos;s
              real perspective.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">Why we don&apos;t allow AI-generated images</h2>
            <p>
              AI image generators are trained on the work of human artists — often without their consent or
              compensation. Allowing AI-generated images on Sparkurio would mean benefiting from that
              extraction while displacing the very creators we want to celebrate. We don&apos;t think that&apos;s right.
            </p>
            <p className="mt-4">
              There&apos;s also a practical reason: AI-generated images dilute the signal. Part of what makes a
              curated board valuable is knowing a human chose every single thing on it. The moment boards
              can be filled with synthetic content, the curation means less.
            </p>
            <p className="mt-4">
              This isn&apos;t about being anti-technology. It&apos;s about protecting the thing that makes Sparkurio
              worth using.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">What&apos;s allowed and what isn&apos;t</h2>
            <div className="grid sm:grid-cols-2 gap-4 not-prose">
              <div className="bg-green-50 border border-green-100 rounded-xl p-5">
                <p className="font-semibold text-green-800 mb-3 text-sm uppercase tracking-wide">Allowed</p>
                <ul className="space-y-2 text-sm text-green-900">
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-green-600">✓</span>
                    Photographs you took
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-green-600">✓</span>
                    Artwork by human artists (with proper credit)
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-green-600">✓</span>
                    Screenshots, scans, book covers, film stills
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-green-600">✓</span>
                    Images you have rights to share
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-green-600">✓</span>
                    Edits or collages of real photographs
                  </li>
                </ul>
              </div>
              <div className="bg-red-50 border border-red-100 rounded-xl p-5">
                <p className="font-semibold text-red-800 mb-3 text-sm uppercase tracking-wide">Not allowed</p>
                <ul className="space-y-2 text-sm text-red-900">
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-red-500">✕</span>
                    Images generated by Midjourney, DALL·E, Stable Diffusion, or similar tools
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-red-500">✕</span>
                    AI-upscaled or AI-inpainted images where the AI is the primary author
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-red-500">✕</span>
                    Deepfakes or synthetic faces
                  </li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">How detection works</h2>
            <p>
              We use automated tools to flag images that appear to be AI-generated before they&apos;re published.
              These tools analyze visual patterns that commonly appear in synthetic images. They&apos;re reasonably
              accurate — but not perfect. No detection method is.
            </p>
            <p className="mt-4">
              We also rely on the community. If you see an image that looks AI-generated, you can report it
              from the tack menu. Reported content is reviewed by a human before any action is taken.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">What happens when something is flagged</h2>
            <p>
              If our automated system flags an image, it won&apos;t be published until it&apos;s reviewed. We&apos;ll let
              you know so you can provide context or swap the image for something else.
            </p>
            <p className="mt-4">
              If an already-published image is flagged by the community and confirmed to be AI-generated
              after review, it will be removed and the uploader will be notified. Repeated violations may
              result in account suspension.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">False positives &amp; appeals</h2>
            <p>
              Detection tools make mistakes. If your image was flagged and you believe it was incorrectly
              identified — for example, it&apos;s a real photograph with unusual lighting, or heavily
              post-processed art — please reach out. We&apos;ll take a look and correct any error.
            </p>
            <div className="mt-5 not-prose">
              <a
                href="mailto:admin@sparkurio.com?subject=AI policy appeal"
                className="inline-flex items-center gap-2 px-5 py-2.5 bg-papaya text-white rounded-full text-sm font-medium hover:bg-papaya/90 transition-colors"
              >
                Contact us to appeal
              </a>
            </div>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">Questions?</h2>
            <p>
              If you have questions about this policy or aren&apos;t sure whether something you want to post is
              allowed, just ask:{" "}
              <a
                href="mailto:admin@sparkurio.com"
                className="text-papaya hover:underline"
              >
                admin@sparkurio.com
              </a>
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-ink/5 mt-16">
        <div className="max-w-3xl mx-auto px-6 py-8 flex items-center justify-between text-xs text-ink/30">
          <span>© {new Date().getFullYear()} Sparkurio</span>
          <Link href="/" className="hover:text-ink/60 transition-colors">Back to home</Link>
        </div>
      </footer>
    </div>
  );
}
